### ISSUE TITLE
Add commentary on age and fluctuations

### ISSUE THREAD

**Issue by chrisnorth** [chrisnorth/planckapps#10]
Add comment to age of Universe (too old / too young / just right)

Add comment to CMB map (& power spectrum) about fundamental mode scale (too large/too small) and amplitude (too faint/too bright). Calculate this by comparing location of maximum value of power spectrum.

**Comment by slowe** [comment]
I didn't think the comment about the fundamental mode scale and amplitude should be written over the top of the map and power spectrum as it would obscure them. I've added it to the messages at the bottom. The message about the fundamental scale now shows up all the time (previously it was just when the power spectrum was visible). It adds the note about the ell value when the power spectrum is open.
