### ISSUE TITLE
Wrong CMB for "Our Universe" on load

### ISSUE THREAD

**Issue by chrisnorth** [chrisnorth/planckapps#12]
The "Our Universe" CMB is the same as the "random" Universe when the site loads. As soon as a slider is moved the "Our Universe" changes to be the correct one - I guess it just needs to be set earlier.

**Comment by slowe** [comment]
It can't get set by Javascript any earlier than the document.ready() event. The one you are seeing is set in the HTML. It'll need to be something so what do you suggest as the default universe?

**Comment by chrisnorth** [comment]
Gah, it's a browser issue. In Chrome I see "Our Universe" as the same as "Simulated Universe", as in the screenshot below. In Firefox it works properly...

![image](https://cloud.githubusercontent.com/assets/4124704/7145163/095d5c5a-e2e2-11e4-91b6-aa58fc33d16e.png)

**Comment by slowe** [comment]
This should now work in Firefox and Chrome.
