### ISSUE TITLE
Add measure of "similarity to our Universe"

### ISSUE THREAD

**Issue by chrisnorth** [chrisnorth/planckapps#9]
Remove the "Our Universe" button.

Add a "score" for how similar it is to our Universe (possibly mean square deviation from the correct value?)

Add text to say how similar or dissimilar it is (about 5 stops for different text).

**Comment by slowe** [comment]
@chrisnorth Any ideas what the text stops should say?

* Not like our Universe
* A bit like our Universe
* Very similar to our Universe
* The same as our Universe

**Comment by chrisnorth** [comment]
Sounds good to me.

+----------------------------------------------------------+
| Dr Chris North
| Research Associate, Undergraduate Admissions Tutor &
| Community Engagement Coordinator
| School of Physics and Astronomy, Cardiff University
| chris.north@astro.cf.ac.uk
| +44 (0)29 208 70537
+----------------------------------------------------------+

**Comment by slowe** [comment]
In that case this issue is probably done.
